repos:
- repo: local
  hooks:
    - id: npm-run-format
      name: npm run format
      entry: npm run format
      language: node
      additional_dependencies: ['prettier']
      pass_filenames: false
