name: bug
description: bug report
title: "[bug]: "
labels: ["bug", "triage"]
projects: ["0guanhua0/ucertify-quiz-helper"]
assignees:
  - 0guanhua0
body:
  - type: textarea
    id: details
    attributes:
      label: details
      description: |
        show browser console and upload screenshot

        if possible attach full HTML DOM
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: version
      description: script version
    validations:
      required: true

  - type: textarea
    id: browser
    attributes:
      label: browser version
    validations:
      required: true
