on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node -v
      - run: npm -v
      - run: npm run format && git diff --exit-code
